### ISSUE TITLE
Extracting other languages than Japanese.

### ISSUE THREAD

**Issue by MateuszGiermakowski** [arcusmaximus/VNTranslationTools#106]
I was messing around with extracting the script from kirikiri VN (Senren Banka) that uses PSB format. 
The tool extracts the Japanese script but I was wondering if it's also possible to extract the English and Chinese scripts from the PSB file.

**Comment by Refrain69** [comment]
[https://github.com/marcussacana/SacanaWrapper](url)
this may be of help.
extract like this:
![屏幕截图 2023-01-07 105114](https://user-images.githubusercontent.com/121091208/211128189-33496fdd-b5b5-4d26-bfea-0f4ed86b781d.png)

**Comment by arcusmaximus** [comment]
It would be possible, but the question is why you'd need it. The extraction functionality is meant to be the first step in a translation project - and why would you translate anything but the original language for that?

**Comment by Cosetto** [comment]
Change [this number](https://github.com/arcusmaximus/VNTranslationTools/blob/4cf0749c1cf603d722453bc623c6273a2d4dbe93/VNTextPatch.Shared/Scripts/Kirikiri/KirikiriScnScript.cs#L12) to 1 to dump English script. Here's my version, I made vntextpatch dump .txt script instead of json script, or you can dump to xlsx
[vn.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10367738/vn.zip)
