### ISSUE TITLE
Extension .ini is not supported

### ISSUE THREAD

**Issue by Refrain69** [arcusmaximus/VNTranslationTools#108]
What's wrong with my computer?
![屏幕截图 2023-01-08 203346](https://user-images.githubusercontent.com/121091208/211196257-39390eff-a014-4905-8ef0-b6f17f970301.png)
Cannot use VNTextPatch,neither the old version nor the newest one.

**Comment by Cosetto** [comment]
What? I don't remember vntextpatch support any .ini script

**Comment by Cosetto** [comment]
Please make sure your files are in the supported engines list:
![image](https://user-images.githubusercontent.com/81801486/211199621-8669bf99-49a5-46bf-983f-b157b09afbf2.png)

**Comment by Refrain69** [comment]
No,I just want to open scn files with this……:-(
![屏幕截图 2023-01-08 222125](https://user-images.githubusercontent.com/121091208/211201393-f92917a4-f49d-47ed-a901-22bbf7904930.png)

**Comment by Cosetto** [comment]
**DON'T** include other files except .scn in **input** folder, because I'm pretty sure you input the folder contains a .ini file
![image](https://user-images.githubusercontent.com/81801486/211204381-12528ec5-e76c-4a83-b622-d21b0e698b0a.png)
![image](https://user-images.githubusercontent.com/81801486/211204198-a6a44833-4212-44c9-8ff2-4f2cd864f7f8.png)

**Comment by Cosetto** [comment]
And also, vntextpatch doesn't support .ini of krkrz, I mean it's readable if you use krkrextract to decrypt it
![image](https://user-images.githubusercontent.com/81801486/211204901-ff9dc61b-19d5-462e-b7bc-04fdbe698d65.png)

**Comment by Refrain69** [comment]
OMG It's this……
![屏幕截图 2023-01-08 232935](https://user-images.githubusercontent.com/121091208/211205052-5c8bdc9e-f387-463f-af86-0a0ff593ad24.png)
hahaha I'm a fool
