### ISSUE TITLE
(YU-RIS) Inserting translation breaks names format

### ISSUE THREAD

**Issue by Sai-key** [arcusmaximus/VNTranslationTools#111]
This a continuation of the issue closed here:
https://github.com/arcusmaximus/VNTranslationTools/issues/109

The game doesn't break anymore however some of the **characters's names** are getting reinserted in the dialog box rather than in the "character names" box when they use parenthesis. This also doesn't happen all the time just on some lines.

Here is an image of how the dialog should look (non translated version):
![Screenshot 2023-01-26 203819](https://user-images.githubusercontent.com/116866187/214975027-8f635fc1-70b6-4fc1-865a-4170906fd16f.png)

Here is an image of how it looks when translated:
![Screenshot 2023-01-26 203636](https://user-images.githubusercontent.com/116866187/214981101-aafd7651-c131-4a91-92dc-7a747277308b.png)

I'll leave here a piece of our current progress on the translation. Some of the rows on the excel file are not even formatted correctly.

[script.xlsx](https://github.com/arcusmaximus/VNTranslationTools/files/10514527/script.xlsx)

**Comment by arcusmaximus** [comment]
Just like YU-RIS only supports `「」` as quotes by default, it only supports full-width `（）` as parentheses. The translation uses half-width `()`, which the game won't detect as dialogue (making it treat those lines as narration instead).

> Some of the rows on the excel file are not even formatted correctly.

Please be more specific - the file has thousands of lines, and "some rows" doesn't really tell me where the problem is.

**Comment by Sai-key** [comment]
> Just like YU-RIS only supports `「」` as quotes by default, it only supports full-width `（）` as parentheses. The translation uses half-width `()`, which the game won't detect as dialogue (making it treat those lines as narration instead).
> 
> > Some of the rows on the excel file are not even formatted correctly.
> 
> Please be more specific - the file has thousands of lines, and "some rows" doesn't really tell me where the problem is.

Please refer to sheet yst00109 and go to row 69 of  script.xlsx.
The name and dialog is shown in the same cell.

スィーリア　共同生活がはじまって三日目
私はなかなか寝付けない夜をむかえていた。

**Comment by arcusmaximus** [comment]
Looks like this particular game also registers the full-width space as a name separator then. This is not a YU-RIS default, and as such, I won't add it to the default VNTextPatch source code (because it might end up doing wrong splits in other games).

If there are many lines like this, you can customize VNTextPatch to add this separator yourself (see https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Yuris/YurisScenarioScript.cs#L83).
