### ISSUE TITLE
Kirikiri using .txt scenario files

### ISSUE THREAD

**Issue by Tooko1005** [arcusmaximus/VNTranslationTools#118]
I've only found this for one game, [Ushinawareta Mirai o Motomete](https://vndb.org/v4880), but its scenario files are not put in either .scn or .ks, but are just in plain .txt files instead. Is it possible to update the code to include functionality for Kirikiri games that use .txt files? Or is it such a rarity that it's not worth the effort? I've included the scenario files.
[Waramete scenario.zip](https://github.com/arcusmaximus/VNTranslationTools/files/10736896/Waramete.scenario.zip)

**Comment by Cosetto** [comment]
Yea, you can
1st :[This code](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Kirikiri/KirikiriSocScript.cs) to KirikiriTxtScript : KirikiriKsScript and extension to txt
2nd: [This line](https://github.com/arcusmaximus/VNTranslationTools/blob/e0cb1f59f39fc1288292eb9537d2ecf7d0293b7e/VNTextPatch.Shared/Scripts/FolderScriptCollection.cs#L44), add another line for **new KirikiriTxtScript()
3rd: [Add another line](https://github.com/arcusmaximus/VNTranslationTools/blob/e0cb1f59f39fc1288292eb9537d2ecf7d0293b7e/VNTextPatch.Shared/VNTextPatch.Shared.csproj#L90) for KirikiriTxtscript

**Comment by Tooko1005** [comment]
> new KirikiriTxtScript()

This worked, at least to rip the script lines, but it didn't rip the character names, which in the .txt files are bounded by【 】. I know that KirikiriKsScript.cs has [this code](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Kirikiri/KirikiriKsScript.cs#L156l), so it should have picked up the names, but it didn't for some reason. I noticed that it's treating the lines starting with # as names per [this code](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Kirikiri/KirikiriKsScript.cs#L156), but I couldn't figure out how to ignore the # and tell it to point to the 【 】for names.

**Comment by arcusmaximus** [comment]
A much easier way of making VNTextPatch read .txt files as Kirikiri scripts (without making any code changes) is to pass `--format=kirikiriks` to the command line. I added this to the readme.

That being said, for this game it doesn't make sense to have VNTextPatch treat the .txt files as Kirikiri scripts because... they're evidently not Kirikiri scripts. It's already suspicious enough that there's a mix of .ks and .txt (normally it's either one or the other), but the syntax is also completely different. Apparently, the developer took the Kirikiri engine and created their own custom script format on top of it, which VNTextPatch doesn't support.

Since this will be a rare format and considering you already managed to mostly implement it yourself, I'll close this issue.
