### ISSUE TITLE
Please add Artemis Engine Support! (*.pfs)

### ISSUE THREAD

**Issue by bregassa** [arcusmaximus/VNTranslationTools#14]
Can you add a support for artemis engine? 
In Kangoku Academia (https://vndb.org/v19830) , I check that inside *.pfs, the script extension is only *.txt , which I think should be easy to implement in VNTextPatch.

**Comment by Cosetto** [comment]
Artemis also use .ast so you may try sacanawrapper

**Comment by arcusmaximus** [comment]
> script extension is only *.txt , which I think should be easy to implement in VNTextPatch

Sure, it's easy, but still takes more effort than MTLers put in their translations.
![image](https://user-images.githubusercontent.com/133129/148849712-360245d8-1f53-49ea-bbaf-2d46d9bba52a.png)

Support is added. Because the file extension alone is not enough for VNTextPatch to recognize it as an Artemis script, please append `--format=artemis` to the command line.

**Comment by Cosetto** [comment]
> > script extension is only *.txt , which I think should be easy to implement in VNTextPatch
> 
> Sure, it's easy, but still takes more effort than MTLers put in their translations. ![image](https://user-images.githubusercontent.com/133129/148849712-360245d8-1f53-49ea-bbaf-2d46d9bba52a.png)
> 
> Support is added. Because the file extension alone is not enough for VNTextPatch to recognize it as an Artemis script, please append `--format=artemis` to the command line.
[script.zip](https://github.com/arcusmaximus/VNTranslationTools/files/7917696/script.zip)
Could you also add for .ast too? Artemis has 2 kind of scripts txt and ast
