### ISSUE TITLE
Issue running .exe

### ISSUE THREAD

**Issue by pdvt** [arcusmaximus/VNTranslationTools#16]
After compiling, I get the following error:

`C:\Users\shant\source\repos\arcusmaximus\VNTranslationTools\Build\Debug>VNTextPatch extractlocal \Folder script.xlsx`
`Retrieving the COM class factory for component with CLSID {00024500-0000-0000-C000-000000000046} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).`

I've looked up the issue and changed Target CPU to x86 (as recommended [here](https://stackoverflow.com/questions/1036856/retrieving-the-com-class-factory-for-component-with-clsid-xxxx-failed-due-to-t)) but error still persists.

Any help would be much appreciated, thanks :)

**Comment by arcusmaximus** [comment]
VNTextPatch requires Excel to be installed when working with .xlsx files.

If you can't/don't want to install Excel, you can specify a folder instead of an .xlsx file as the extraction target. The tool will then create .txt files. However, these are only minimally supported: you can't have the original and the translation side by side, you can't add comments, line breaks in the original (or in the translation) will mess things up and so on.

**Comment by pdvt** [comment]
Thanks, got it to work! Much appreciated.

Any idea how to get italics to work in BGI, and otherwise edit fonts?

**Comment by arcusmaximus** [comment]
I'm not aware of any control codes in BGI for this. You may be able to get it working with VNTextProxy from this repository instead. It can make VN engines use an arbitrary font (even one that's not installed on the user's machine), as well as pick up special markers in the text and toggle bold/italic/underline accordingly.

The markers are added by VNTextPatch, but currently only for a few script formats not including BGI. You can look at SystemNnnBaseScript for an example if you want to try it yourself.
