### ISSUE TITLE
Text Proxy doesn't work (SystemNNN game)

### ISSUE THREAD

**Issue by KuronekoRM** [arcusmaximus/VNTranslationTools#18]
Hi!
I'm trying to reinsert translated text with spanish characters in a SystemNNN game, Clover Toshokan no Juunintachi. The text shows almost perfectly, but the spanish characters appear as a circle.
I've followed the instructions and, after replacing the .spt I unpacked and repacked using the TextPatch tool, put these files in the same folder as the .exe of the game:
ARIAULUNI.TFF (the font, Arial Unicode MS)
d2d1.dll
sjis_ext.bin
This game has a nnnConfig2.exe file that lets you choose a 'custom font', but only accepts japanese fonts. Even if I choose a font which should have spanish characters (such as Tahoma or Arial Unicode MS), those characters still won't look as intended.

**Comment by eliasstein** [comment]
Hola @KuronekoRM si estas interesado/a puedo ayudarte a solucionar ese problema de las tildes mi discord es
kutakikaari#5195

**Comment by KuronekoRM** [comment]
> kutakikaari#5195

¡Gracias! Te envié una solicitud (es la cuenta que tiene #5533)

**Comment by arcusmaximus** [comment]
The font selected in nnnConfig2.exe doesn't matter - whichever font the game tries to load, VNTextProxy will replace it by the .ttf file it found.

All I can say is that the proxy has already been used successfully in several SystemNNN translations with non-SJIS characters. I'd suggest building it in debug mode, attaching Visual Studio to the game, placing a breakpoint in `SjisTunnelDecoder::Decode()`, and seeing what's going wrong.

As a side note, if you intend to use a builtin Windows font like Arial, you can change `Proportionalizer::LoadCustomFont()` to simply return the font's name rather than loading a .ttf file.
