### ISSUE TITLE
Missing text of Sakura no Uta(Ethornell)

### ISSUE THREAD

**Issue by Cosetto** [arcusmaximus/VNTranslationTools#26]
The missing text belongs to the backlog because it is illustrated by imagines
![image](https://user-images.githubusercontent.com/81801486/159291784-7db4d032-d36e-4479-897a-1253a9136737.png)
[00_op_01.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8316571/00_op_01.zip)

**Comment by Perturbed-Pangolin** [comment]
We've run into seemingly the same issue for Senmomo (also Ethornell) where some lines of dialog are replaced by images during normal gameplay but still appear normally in the backlog, and those weren't picked up by VNTextPatch. this was caused by the fact that these "hidden messages" are handled by a different opcode (0x0143), so our fix was to treat those as regular messages by changing this dictionary here: https://github.com/arcusmaximus/VNTranslationTools/blob/95bf4b03d10864aa29a2fa82db43104549c0dbc3/VNTextPatch.Shared/Scripts/Ethornell/EthornellV1Disassembler.cs#L502-L510
to this:
```cs
            _operandReaders =
                new Dictionary<int, Action>
                {
                    { 0x0003, ReadPushStringAddressOperand },
                    { 0x001C, HandleUserFunctionCall },
                    { 0x0140, HandleMessage },
                    { 0x0143, HandleMessage },
                    { 0x0160, HandleChoiceScreen }
                };
```
a warning that this is not exactly a clean fix, as (for us at least) it failed to extract the speaker names, resulting in a "not enough strings in spreadsheet" error when running `insertlocal`. which you can work around by adding some blank spaces in the speaker name column for these specific lines in your extracted spreadsheet

**Comment by Cosetto** [comment]
> > The missing text belongs to the backlog because it is illustrated by imagines ![image](https://user-images.githubusercontent.com/81801486/159291784-7db4d032-d36e-4479-897a-1253a9136737.png) [00_op_01.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8316571/00_op_01.zip)
> 
> Hey, could you tell me how you got any text at all? I get an dictionary error everytime I try to unpack an .arc file from Sakura No Uta.

well I used GARbro to extract dataxxxx.arc and vntextpatch to extract them

**Comment by anphex** [comment]
Ohh, I thought you could just feed it an .arc file. Now it worked for me too. Thank you so much!

**Comment by arcusmaximus** [comment]
Fixed.
