### ISSUE TITLE
Issues in lines because furigana characters in ArcGameEngine (.bin)

### ISSUE THREAD

**Issue by Berthog** [arcusmaximus/VNTranslationTools#47]
Hello, today I tested the tools with ArcGameEngine (eushully games) and found some things that in fact aren't a big problem (depeding of the person) it would be nice to adjust. It seems the program divides the dialogue lines, the words with furigana and the furigana itself in diferents lines, making this as result: 
![image](https://user-images.githubusercontent.com/84604636/166826780-ee09bf8c-67d1-4f86-b8f2-20e34d13df51.png)
While sometimes furiganas in this kind of games are useful, there's times that are pretty usuless in a translation, and since one line alone can be divided into 3 differents line, there are times when script can turn in a mess and more in eushully games where are a high amount of furiganas. Is possible to divide the furiganas in a separate columm and merged the original word with its proper line? Tool tested on [Amayui Castle Meister](https://vndb.org/v20418) and [Madou Koukaku](https://vndb.org/v11620) but I'm sure it happens in all eushully games. 
I'm attaching some script files here just in case. 
[amayui.zip](https://github.com/arcusmaximus/VNTranslationTools/files/8627268/amayui.zip)

**Comment by Berthog** [comment]
I know I asked this time ago, but a friend made a code in python to fix this issue. The problem is that you first have to create a decompiled file and then use the code over that decompiled .txt in order to get the strings like this: 
![image](https://user-images.githubusercontent.com/84604636/197369793-776da613-3b97-4bdf-93b4-c5db328b4089.png)
So I'm adding the code here just in case it could be helpful for a cleaner script dump with vntextpatch.
[Download link](https://drive.google.com/file/d/1kv_uGkg16swqzKWjEiCeO3fOw8ybUkI-/view?usp=sharing)

**Comment by arcusmaximus** [comment]
I started on this a while ago too, but it took time because I had to reverse engineer the game and figure out all the control transfer instructions. After all, if you want to change furigana in a script, you need to insert/remove instructions, which in turn means you need to adjust all the jump instructions around them.

Apart from furigana (and line breaks), VNTextPatch now also supports AGE character names from CHINIT.BIN. To translate those names, you can simply change them in the scenarios; no need to translate the CHINIT sheet.

After this effort, I do hope you won't use the result to create a machine translation :)
