### ISSUE TITLE
Weird gaps after Line-breaks of Yu-RIS

### ISSUE THREAD

**Issue by xenei** [arcusmaximus/VNTranslationTools#5]
Hey @arcusmaximus,
Last time I made a issue about how there's certain 2 letters gap after Line-breaks which is indeed weird, and you suggested me to decompile then find and fix it...
But I finally figured out what the problem is! It is either the repacking of the scripts or I think your tool is doing... Because I manually edited the game and there's was no weird gaps, here's the proof - 
![gap](https://user-images.githubusercontent.com/91423244/145713129-6c0c3ac3-3555-457e-b549-71e00eebfb21.PNG)
So the pic above is the one with your tool, you can see the weird gaps...
And here this one is mine, which I edited and manually added \r\n then repacked using one chinese tool (which doesn't work with clock-Ups..) and the result is - 
![Capture](https://user-images.githubusercontent.com/91423244/145713322-e171d5bb-f0c2-4666-b003-40a79af5b2e2.PNG)
As you can see the problem was not that the company modified their scripts but something that your tool is doing it (please don't take this offensively) 
the game I tested here is this - https://vndb.org/v16133
Now I humbly request you to please look into this matter because I think something is wrong with repacking script, And your tool is the only tool that works with Clock-UP Vns... 
`Note:` This issue is happening with some particular VNs only so it is not that the Repacking script is entirely doing anything wrong, but with VNs like this; something sure is wrong here with the tool
Thank you and best regards,
xenei

**Comment by xenei** [comment]
And it looks like the fix? I think so... Is to add 2 letters gap after \r\n then repack with your tool. But that however is just a temporary fix for what I've found...

**Comment by arcusmaximus** [comment]
Not offended, just confused :)

I checked the code of the Chinese tool and found no special handling for line breaks (seems like it would copy the `0D 0A` straight into the .ybn file). Meanwhile, my own tool replaces `0D 0A` by the YU-RIS control code `EF F0`. The reason for this is that YU-RIS doesn't actually recognize `0D 0A` (displays it as two spaces instead). 夏ノ鎖 is no exception:

![image](https://user-images.githubusercontent.com/133129/146587331-6a42938e-f475-437b-a1a6-5cd314ec8e04.png)

I'm also not sure what you mean by adding a 2 letter gap after \r\n. If you mean adding a few spaces after the \r\n, well, the only result of that is... a few extra spaces:

![image](https://user-images.githubusercontent.com/133129/146587683-3eae7606-475e-4f15-b5fc-6c0dca5aad22.png)

Are you sure that the Chinese tool actually turns line breaks in the .json into real line breaks ingame? For that particular narration line in the ギャル screenshot, it looks like using two spaces instead of \r\n might, by coincidence, have had the same result.

If you're certain that the Chinese tool creates working line breaks, could you send a sample .ybn along with ysc.ybn so I can see what's in there? (I'm having a hard time finding the non-Clock UP VNs you listed, so I can't test the tool on my own)

**Comment by xenei** [comment]
First of all, I want to say that I've come to understand, Clock-UP VNs are a no go, they seem to require absolute font change without it, it looks horrible even if everything is done manually.
And you're right, The Chinese tool doesn't have any line-break code rather it's adding 2 spaces, I've come to know that after my last post here. But with your tool I encounter weird gaps with these particular VNs when I don't with other VNs like `Hitotsumami ~Relaxation Series~` from same dev `Herencia`. I am adding the link for `Gyaru Kanshu Rina-chan no M Otoko-ka Seikyouiku Shidou`, if you'd like to test that VN, please do so.   **Game** `LINK` ―― [Drive](https://drive.google.com/file/d/19dKvG6yGw0SsLhp8a1Pads5qpsVXqD1c/view?usp=sharing)
Finally I want to say that I'm very thankful for this tool, honestly. I'm using your tool to add word-wrap on my current [Anim](https://vndb.org/v18837) project, ahahaha. And working on these Yu-RIS Vns as my side project but still the giving the importance it needs. 

Thank you and best regards.
xenei

**Comment by xenei** [comment]
Also If I may ask, do you have Discord or email for better communication with you? It's entirely ok if you don't, I was just curious and wanted to ask about it. Thanks.

**Comment by arcusmaximus** [comment]
Changing the font can be done with the VNTextProxy DLL in this repository. However, a different font still won't fix the gaps. As mentioned in the previous issue, this would likely require decompiling, editing, and recompiling the .ybn files responsible for text layout. (If you can find such a decompiler at all - I sure can't)

Alternatively, if you have a working game that uses the same YU-RIS version as a buggy game, it *might* be possible to just overwrite the buggy .ybn files with the corresponding working ones. You'd have to:
* Read the yst_list.ybn of both games to find the indexes (and thereby .ybn names) of the text layouting scripts. (See [YU-RIS notes](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextPatch.Shared/Scripts/Yuris/Notes.txt#L78) for a description of the file format)
* Rename the .ybns of the working game to use the indexes of the broken game
* Put the renamed working .ybns in the broken game

Apart from this suggestion, though, I'm afraid I can't help you for these games. I do wish you good luck with your Musumama project.

**Comment by arcusmaximus** [comment]
Then again, a bird told me you do machine translation.

![image](https://user-images.githubusercontent.com/133129/146812574-50004dd8-79e5-48d9-aa44-db236e26db91.png)
