### ISSUE TITLE
extractgdocs

### ISSUE THREAD

**Issue by nightpool** [arcusmaximus/VNTranslationTools#50]
Hi, I'm trying to extract kirikiri files to translate them, but I'm having a hard time because I don't have Excel installed locally. Having an `extractgdocs` command to go with the `insertgdocs` command would be very useful.

**Comment by arcusmaximus** [comment]
While I didn't implement `extractgdocs`, I did switch VNTextPatch over to a third party library that reads and writes .xlsx files directly rather than going to Excel. This means you can now use `extractlocal` to create an .xlsx file (without having Excel installed), and then upload it to Google Docs for editing.

**Comment by nightpool** [comment]
wow, thank you for the quick response! that's amazing to hear. I started implementing the gdocs export last night, but my c# skills are very poor, so this is definitely easier 😅
