### ISSUE TITLE
SJIS tunneling doesn't work under Wine

### ISSUE THREAD

**Issue by latin-1** [arcusmaximus/VNTranslationTools#92]
The `d2d1.dll` appears to be loaded, but `sjis_ext.bin` has no effect on the text.

**Comment by Cosetto** [comment]
Use CFF explorer to see what proxy the game prefer. 
![image](https://user-images.githubusercontent.com/81801486/206115136-8d85b39a-f9fe-42c9-962c-dd8279539d14.png)
And some games use D2D instead of GDI, uncomment and add comment [these line](https://github.com/arcusmaximus/VNTranslationTools/blob/4b7b0b52c7ccd1a1d0d9119f4d18c9889f6911cd/VNTextProxy/dllmain.cpp#L34-L36), choose 1 only

**Comment by latin-1** [comment]
@Cosetto I'm sorry but this is unrelated to my problem. The game works fine under Windows, but not under Wine.
> Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, macOS, & BSD.

**Comment by arcusmaximus** [comment]
In that case, please create a Wine ticket instead.
